### ISSUE TITLE
关于MNNOCRDetPostProcess类中ClipperLib.clipperOffset?

### ISSUE THREAD

**Issue by MaShiZhao** [luoqianlin/mnn-android-ocr-demo#3]
你好，
请问在MNNOCRDetPostProcess类里面的代码是纯手写的嘛？
关于这里面中的ClipperLib.clipperOffset方法是怎么知道使用该c++文件呢？
谢谢

**Comment by luoqianlin** [comment]
手写的，属于java调用c++，使用JNI

**Comment by luoqianlin** [comment]
> 你好，
> 请问在MNNOCRDetPostProcess类里面的代码是纯手写的嘛？
> 关于这里面中的ClipperLib.clipperOffset方法是怎么知道使用该c++文件呢？
> 谢谢

手写的，属于java调用c++，使用JNI

**Comment by MaShiZhao** [comment]
> > 你好，
> > 请问在MNNOCRDetPostProcess类里面的代码是纯手写的嘛？
> > 关于这里面中的ClipperLib.clipperOffset方法是怎么知道使用该c++文件呢？
> > 谢谢
> 
> 手写的，属于java调用c++，使用JNI

你好 想问下为啥你的libMNN.so文件76M,我的只有875k 我看其他人的也都是比较小的

**Comment by luoqianlin** [comment]
重新编译了动态库大小正常了
